#!/usr/bin/env bash


# Force tmux to assume the terminal supports 256 colours.
alias tmux='tmux -2 '

alias vi='nvim '
alias vim='nvim '
alias view='nvim -R '
alias vimdiff='nvim -d '

alias sudo='sudo '
alias tree='tree -C'

if [ $(uname) = "Linux" ]; then
    alias ls='ls --color=auto '
else
    alias ls='ls -G '
fi

if [ $(uname) = "Darwin" ]; then
    alias chrome='/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome '
    alias canary='/Applications/Google\ Chrome\ Canary.app/Contents/MacOS/Google\ Chrome\ Canary '
    alias canary-debug-canary='canary --remote-debugging-port=9222'
fi

alias l='ls '
alias ll='ls -al '

alias r='ranger --choosedir=$HOME/rangerdir; LASTDIR=`cat $HOME/rangerdir`; cd "$LASTDIR"'

# not committed
alias poweroff='sudo systemctl poweroff'
alias reboot='sudo systemctl reboot'
alias i3-exit='i3-msg exit'
