#!/usr/bin/env bash


# Force tmux to assume the terminal supports 256 colours.
alias tmux='tmux -2 '

alias vi='nvim '
alias vim='nvim '
alias view='nvim -R '

alias sudo='sudo '
alias tree='tree -C'

if [ $(uname) = "Linux" ]; then
    alias ls='ls --color=auto '
else
    alias ls='ls -G '
fi

alias l='ls '
alias ll='ls -al '

alias r='ranger --choosedir=$HOME/rangerdir; LASTDIR=`cat $HOME/rangerdir`; cd "$LASTDIR"'
